TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/ViewModels/FacultyResearchInterestViewModel.cs
namespace TraineeTrackingSystem.Web.ViewModels
{
    public class FacultyResearchInterestViewModel
    {
        
        public int Id { get; set; }
        public string ResearchInterest { get; set; }
    }
}

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/ViewModels/FacultyResearchInterestsViewModel.cs
using System;
using System.Collections.Generic;

namespace TraineeTrackingSystem.Web.ViewModels
{
    public class FacultyResearchInterestsViewModel
    {
        public Guid PersonId { get; set; }
        public int? SelectedId { get; set; }

        public string SelectedResearchInterest { get; set; }

        public IEnumerable<FacultyResearchInterestViewModel> FacultyResearchInterests { get; set; }
    }
}

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Controllers/FacultyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using TraineeTrackingSystem.Common;
using TraineeTrackingSystem.Repository;
using TraineeTrackingSystem.Data;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using TraineeTrackingSystem.Web.Common;
using TraineeTrackingSystem.Web.PostModels;
using TraineeTrackingSystem.Web.ViewModels;
// added tracking date and user update
using System.Security.Claims;
using TraineeTrackingSystem.Web.Models;

namespace TraineeTrackingSystem.Web.Controllers
{
    [AuthorizeUser(AccessLevel = "Editor")]
    //[AuthorizeUser(MultipleRoles = "Administor, SuperUser,Editor")]
    public class FacultyController : Controller
    {
        private readonly FacultyRepository facultyRepository;
        private readonly PersonRepository personRepository;
        private readonly CommonDataRepository commonRepository;
        private const string firstName = "";
        private const string lastName = "";
        private const string middleName = "";
        private readonly string _DATEFORMAT = "{0:yyy-MM-dd}";
        private readonly string _LastUpdateDATEFORMAT = "{0:M/dd/yyy hh:mm:tt}";

        private readonly TTSEntities _context;

        public FacultyController()
        {
            _context = new TTSEntities();
            facultyRepository = new FacultyRepository(_context);
            personRepository = new PersonRepository(_context);
            this.commonRepository = new CommonDataRepository(_context);
        }

        protected override void Dispose(bool disposing)
        {
            facultyRepository.Dispose();
            base.Dispose(disposing);
            commonRepository.Dispose();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        [AcceptVerbs(HttpVerbs.Get)]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        //[AuthorizeUser(AccessLevel = "SuperUser, Administrator, Editor")]
        public ActionResult Index()
        {

            var facultyDemographics = facultyRepository.GetSearch_VwFacultyDemographics();
            return View(facultyDemographics);
        }

        public ActionResult UpdateDegree(DegreePostModel updateDegreeModel)
        {
            bool isNew = !updateDegreeModel.Id.HasValue || !_context.Set<FacultyAcademicData>()
                .Any(o => o.Id == updateDegreeModel.Id);
            var degreeInfo = isNew
                ? new FacultyAcademicData() : _context.Set<FacultyAcademicData>().Find(updateDegreeModel.Id);
            if (_context.Set<AcademicDegree>().Any(ac => ac.Name == updateDegreeModel.AcademicDegree))
            {
                AcademicDegree academicDegree=_context.Set<AcademicDegree>()
                    .Single(ac => ac.Name == updateDegreeModel.AcademicDegree);
                degreeInfo.AcademicDegreeId = academicDegree.Id;
            }

            if (updateDegreeModel.DegreeYear > 0)
            {
                degreeInfo.DegreeYear = updateDegreeModel.DegreeYear;
            }
            degreeInfo.DateLastUpdated = DateTime.Now;
            degreeInfo.LastUpdatedBy = (((ClaimsPrincipal)User).Claims.Where(p => p.Type == ClaimTypes.Name).FirstOrDefault().Value);

            Institution institution=null;

            if (_context.Set<Institution>().Any(ac => ac.Name == updateDegreeModel.Institution))
            {
                institution = _context.Set<Institution>().Single(ac => ac.Name == updateDegreeModel.Institution);
                degreeInfo.InstitutionId = institution.Id;
            }
                
            
            degreeInfo.PersonId = updateDegreeModel.PersonId;
            if (isNew)
            {
                _context.Set<FacultyAcademicData>().Add(degreeInfo);
            }
            _context.SaveChanges();

            
            var degreeViewModel = new AcademicDegreeViewModel
            {
                Id=degreeInfo.Id,
                //AcademicDegreeName=updateDegreeModel.AcademicDegree,
                AcademicDegreeName = updateDegreeModel.AcademicDegree != null ? updateDegreeModel.AcademicDegree : string.Empty,
                InstitutionId = institution != null ? institution.Id : 0,
                InstitutionName = institution != null ? institution.Name : string.Empty,
                DegreeYear = updateDegreeModel.DegreeYear,
                CityName = institution.City,
                StateName = institution.StateProvince != null ? institution.StateProvince.FullName : string.Empty,
                CountryName = institution.Country != null ? institution.Country.Name : string.Empty,
                StrDateLastUpdated = (degreeInfo.DateLastUpdated != null) ? String.Format(_LastUpdateDATEFORMAT, degreeInfo.DateLastUpdated) : string.Empty,
                StrLastUpdatedBy = commonRepository.GetLoginInfo(degreeInfo.LastUpdatedBy),
            };

            return new JsonCamelCaseResult(degreeViewModel,JsonRequestBehavior.AllowGet);
        }


        public ActionResult DeleteDegree(int id)
        {
            var facultyDegree = _context.Set<FacultyAcademicData>().Find(id);
            if (facultyDegree != null)
            {
                _context.Set<FacultyAcademicData>().Remove(facultyDegree);
                _context.SaveChanges();
            }
            return Json(id);
        }

        public ActionResult UpdateResearchInterest(ResearchInterestPostModel updateDegreeModel)
        {
            //check if it's a new or existing reseach interest
            bool isNew = !updateDegreeModel.Id.HasValue || !_context.Set<FacultyResearchInterest>().Any(fr => fr.Id == updateDegreeModel.Id);
            var facultyResearchInterest = isNew
                ? new FacultyResearchInterest()
                : _context.Set<FacultyResearchInterest>().Find(updateDegreeModel.Id);
            //facultyResearchInterest.DateEntered = updateDegreeModel.DateEntered;
            facultyResearchInterest.ResearchInterest = updateDegreeModel.ResearchInterest;
            facultyResearchInterest.PersonId = updateDegreeModel.PersonId;
            if (isNew)
            {
                _context.Set<FacultyResearchInterest>().Add(facultyResearchInterest);
            }
            _context.SaveChanges();
            return Json(facultyResearchInterest.Id);
        }

        public ActionResult DeleteResearchInterest(int id)
        {
            var facultyResearchInterest = _context.Set<FacultyResearchInterest>().Find(id);
            if (facultyResearchInterest != null)
            {
                _context.Set<FacultyResearchInterest>().Remove(facultyResearchInterest);
                _context.SaveChanges();
            }
            return Json(id);
        }

        public ActionResult CreateFaculty(PersonPostModel newPersonModel)
        {
            
            //Create Person, get person Id, and then create faculty
            var newPerson=new Person
            {
                PersonId=Guid.NewGuid(),
                FirstName = newPersonModel.FirstName,
                LastName = newPersonModel.LastName,
                MiddleName = newPersonModel.MiddleName,
                //GenderId = newPersonModel.GenderPersonId.HasValue ? newPersonModel.GenderPersonId.Value: 0,
                //GenderAtBirthId = newPersonModel.GenderOfBirthPersonId.HasValue ? newPersonModel.GenderOfBirthPersonId.Value: 0,
                //EthnicityId = newPersonModel.EthnicityPersonId.HasValue ? newPersonModel.EthnicityPersonId.Value: 0,

                DateLastUpdated = DateTime.Now,
                LastUpdatedBy = (((ClaimsPrincipal)User).Claims.Where(p => p.Type == ClaimTypes.Name).FirstOrDefault().Value)
            };
            //if (newPersonModel.EmployeeId ==null)
            //{
            //    return View();
            //}
            Faculty newFaculty = facultyRepository.AddFaculty(newPerson, newPersonModel.EmployeeId);
            return Json(newFaculty.Id);
        }

        public ActionResult UpdateFaculty(PersonPostModel updatePersonModel)
        {
            var faculty = _context.Set<Faculty>()
                .Include(f => f.Person)
                .Single(f => f.Id == updatePersonModel.Id);
           
            faculty.Person.FirstName = updatePersonModel.FirstName;
            faculty.Person.LastName = updatePersonModel.LastName;
            faculty.Person.MiddleName = updatePersonModel.MiddleName;
            faculty.EmployeeId = updatePersonModel.EmployeeId;

            faculty.PositionDepartmentId = updatePersonModel.PositionDepartmentId.HasValue ? updatePersonModel.PositionOrganizationId.Value: 0;
            faculty.PositionDepartmentId = updatePersonModel.PositionOrganizationId.HasValue ? updatePersonModel.PositionOrganizationId.Value: 0;
            faculty.MentorId = updatePersonModel.MentorId.HasValue ? updatePersonModel.MentorId.Value: Guid.Empty;
            Person personRecTobeUpdated = null;
            if (_context.Set<Person>().Any(p => p.PersonId == updatePersonModel.PersonId))
            {
                personRecTobeUpdated = _context.Set<Person>().Single(p => p.PersonId == updatePersonModel.PersonId);
                if (updatePersonModel.GenderId != null && updatePersonModel.GenderId != 0){
                    personRecTobeUpdated.GenderId = updatePersonModel.GenderId;
                }
                if (updatePersonModel.GenderAtBirthId != null && updatePersonModel.GenderAtBirthId != 0){
                    personRecTobeUpdated.GenderAtBirthId = updatePersonModel.GenderAtBirthId;
                }
                if (updatePersonModel.EthnicityId != null && updatePersonModel.EthnicityId != 0){
                    personRecTobeUpdated.EthnicityId = updatePersonModel.EthnicityId;
                }
            }

            /// MVN - these codes are no longer needed
            ///faculty.OtherAffiliations = updatePersonModel.OtherAffiliations;

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Controllers/FacultyResearchInterestsController.cs
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Http;
using System.Web.Http.Description;
using TraineeTrackingSystem.Data;

namespace TraineeTrackingSystem.Web.Controllers
{
    public class FacultyResearchInterestsController : ApiController
    {
        private TTSEntities db = new TTSEntities();

        // GET: api/_FacultyResearchInterests
        public IQueryable<FacultyResearchInterest> GetFacultyResearchInterests()
        {
            return db.FacultyResearchInterests;
        }

        // GET: api/_FacultyResearchInterests/5
        [ResponseType(typeof(FacultyResearchInterest))]
        public IHttpActionResult GetFacultyResearchInterest(int id)
        {
            FacultyResearchInterest facultyResearchInterest = db.FacultyResearchInterests.Find(id);
            if (facultyResearchInterest == null)
            {
                return NotFound();
            }

            return Ok(facultyResearchInterest);
        }

        // PUT: api/_FacultyResearchInterests/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutFacultyResearchInterest(int id, FacultyResearchInterest facultyResearchInterest)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != facultyResearchInterest.Id)
            {
                return BadRequest();
            }

            db.Entry(facultyResearchInterest).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FacultyResearchInterestExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/_FacultyResearchInterests
        [ResponseType(typeof(FacultyResearchInterest))]
        public IHttpActionResult PostFacultyResearchInterest(FacultyResearchInterest facultyResearchInterest)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.FacultyResearchInterests.Add(facultyResearchInterest);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = facultyResearchInterest.Id }, facultyResearchInterest);
        }

        // DELETE: api/_FacultyResearchInterests/5
        [ResponseType(typeof(FacultyResearchInterest))]
        public IHttpActionResult DeleteFacultyResearchInterest(int id)
        {
            FacultyResearchInterest facultyResearchInterest = db.FacultyResearchInterests.Find(id);
            if (facultyResearchInterest == null)
            {
                return NotFound();
            }

            db.FacultyResearchInterests.Remove(facultyResearchInterest);
            db.SaveChanges();

            return Ok(facultyResearchInterest);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool FacultyResearchInterestExists(int id)
        {
            return db.FacultyResearchInterests.Count(e => e.Id == id) > 0;
        }
    }
}

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Faculty/Edit.cshtml
@model EditFacultyViewModel
@{
    ViewBag.Title = "Edit Faculty";
}
<div class="page-context">
    <div class="context-wrapper">
        <h1 class="page-title">Faculty Form</h1>
    </div>
</div>
<div class="content form">
    <article class="content">
        <p class="reminder">Please be sure to save each section as you make edits/updates.</p>
        <!--DONE WITH FORM BUTTON-->
        <button class="submit done" data-toggle="modal" data-target="#myModal">
            Done
        </button>

        <h1 class="section-title">General Information</h1>   
        <p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.PersonGeneralViewMoel.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.PersonGeneralViewMoel.LastUpdatedBy)) </p> 
        <fieldset name="FacultyGeneralInfo" id="FacultyGeneralInfo" class="two-column-fields">
            @{Html.RenderPartial("_FacultyGeneral", Model.PersonGeneralViewMoel);}
        </fieldset>    
        <h1 class="section-title">Appointments Information</h1>    
        <fieldset name="FacultyAppointmentInfo" id="FacultyAppointmentInfo" class="two-column-fields">
            @{Html.RenderPartial("_FacultyAppointmentInfo", Model.ApointmentInformations);}
        </fieldset>

        <h1 class="section-title">Academic Information</h1>
        <fieldset name="FacultyAcademicInfo" id="FacultyAcademicInfo" class="two-column-fields">
            @{Html.RenderPartial("_FacultyAcademicInformation", Model.AcademicInformations);}
        </fieldset>
        @*MVN 3/16/2016 ->commented this out - per Leslie request as we are no longer needed*@ 
        @*<h1 class="section-title">Degree Information</h1>
        <fieldset name="FacultyAcademicDegree" id="FacultyAcademicDegree" class="two-column-fields">
            @{Html.RenderPartial("_FacultyDegree", Model.DegreeInformations);}
        </fieldset>*@
        <h1 class="section-title">Mentee Information</h1>
        <fieldset name="FacultyMentee" id="FacultyMentee" class="two-column-fields">
            @{Html.RenderPartial("_FacultyMenteeMentors", Model.MenteesGridView);}
        </fieldset>

        <h1 class="section-title">Research Interest Information</h1>
        <fieldset name="FacultyResearchInterest" id="FacultyResearchInterest" class="two-column-fields">
            @{Html.RenderPartial("_FacultyResearchInterest", Model.FacultyResearchInterests);}
        </fieldset>

        <h1 class="section-title">Funding Information</h1>
        <fieldset name="FundingInformation" id="FundingInformation" class="two-column-fields">
            @{Html.RenderPartial("_FacultyFundingInformation", Model.FundingGridView);}
        </fieldset>
        
        <fieldset name="OtherFundingInfo" id="OtherFundingInfo" class="two-column-fields">
            @{Html.RenderPartial("_FacultyOtherFundingInfo", Model.OtherGridView);}
        </fieldset>
        
        <!--DONE WITH FORM BUTTON-->
        <button class="submit done" data-toggle="modal" data-target="#myModal">
            Done
        </button>
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">Exit Confirmation</h4>
                    </div>
                    <div class="modal-body">
                        This action will take you to the menu, and unsaved changes will be lost.
                    </div>
                    <div class="modal-footer">
                        <button class="add-section" onclick="window.location = '@Url.Content("~/Faculty/Index/")'">OK</button>
                        <button type="button" class="add-section" data-dismiss="modal">Cancel</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
</article>
</div>

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Faculty/Index.cshtml
@using TraineeTrackingSystem.Web.Models;
@model IEnumerable<Search_VwFacultyDemographics>
@{
    ViewBag.Title = "Faculty Index";
}

<div class="page-context">
    <div class="context-wrapper">
        <h1 class="page-title">Faculty</h1>
    </div>
</div>
<div class="content form">
    <article class="content">
        @*@if (SecurityControl.IsAdminUser(this.User) || 
             SecurityControl.IsEditUser(this.User) ){*@ 
        @if (SecurityControl.IsReaderUser(this.User)) { 
            <div class="section-admin">
                @using (Html.BeginForm("Create", "Faculty"))
                {
                    <button type="submit" class="add-item program">+ Add Faculty</button>
                }
            </div>
            <div class="wide-grid">
                <div id="clientsDb">
                        @{Html.RenderPartial("_FacultyLandingPage", Model);}
                </div>
            </div>
        }

    </article>
</div>

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Faculty/_FacultyFundingInformation.cshtml
@using TraineeTrackingSystem.Web.Common
@model InstitutionTrainingGrants

<div id="funding_Inst_view">
    <input id="reseachId" type="hidden" data-bind="value: selectedId" />
    <h2 class="section-title">Institutional Training Grants</h2>
    <script type="text/x-kendo-template" id="othergrant-viewLink">
        <div>
            <span>
                <a href='@Url.Action("", "")/TrainingGrant/Edit/#= trainingGrantId #'>
                    View Grant^
                </a>
            </span>
        </div>
    </script>

    @*MVN - keep these for future REF*@
    @*<script id="startDateTemplate" type="text/x-kendo-template">
            #= kendo.toString(kendo.parseDate(dateTimeFundingStarted, 'yyyy-MM-dd' ), 'MM/dd/yyyy' ) #
    </script>

    <script id="endDateTemplate" type="text/x-kendo-template">
        #= kendo.toString(kendo.parseDate(dateTimeFundingEnded, 'yyyy-MM-dd' ), 'MM/dd/yyyy' ) #
    </script>*@

    <div class="grid-note">
        These are Pending and Active Training Grants that are associated with this Faculty Member.<br />
        To Add, go to <a href='@Url.Action("", "")/TrainingGrant/'>Training Grants</a> menu.
        <br /><br />
        <b>^</b> = <small>Clicking this link will take you off this page -- you may lose unsaved changes.</small>
    </div>

    <div id="fundingInstGrid" data-role="grid"
         data-editable="false"
         data-selectable="false"
         data-scrollable="true"
         data-sortable="true"
         data-pageable='{ "pageSize": 5 }'
         data-columns="[
                       { 'field': 'trainingGrantId'},
                       {title:'Role','field':'facultyPrimaryRole'},
                       {title:'Title','field': 'title'},
                       {title:'Sponsor','field':'sponsorName'},
                       {title:'Sponsor Award #',width:120,'field':'sponsorAwardNumber'},
                       {title:'Start Date','field': 'strDateTimeFundingStarted'},
                       {title:'End Date','field': 'strDateTimeFundingEnded'},
                       {title:'Action', 'width': '130px', template:kendo.template($('#othergrant-viewLink').html() ) }
         ]"
         data-bind="source: fundingGridView">
    </div>
</div>

<script>
    $(document).ready(function () {
        var fundingInstVM = kendo.observable($.extend({
            fundingGridView: new kendo.data.DataSource({
                type: "json",
                serverFiltering: true,
                transport: {
                    read: {
                        url:'@Url.Content("~/CommonData/GetFundingInstTrainingGrantList")',
                        datatype:"json",
                        data: {
                            name: function(){
                                return $("#fundingInstGrid").data("grid").value();
                            }
                        }
                    }
                }
            }),
        },@(Html.ToJson(Model))));
        //window.console && console.log(fundingInstVM);
        kendo.bind($("#funding_Inst_view"), fundingInstVM);
        $("#fundingInstGrid").data("kendoGrid").hideColumn(0);
    })
</script>

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Faculty/_FacultyLandingPage.cshtml
@model IEnumerable<Search_VwFacultyDemographics>

<div id="clientsDb"> 
    @(Html.Kendo().Grid(Model)
          .Name("grid")
          .Columns(columns =>
          {
              columns.Bound(c => c.EmployeeId).Title("ID").Width(20);
              columns.Bound(c => c.FullName).ClientTemplate(@Html.ActionLink("#=FullName#", "Edit", new { ID = "#=Id#" }).ToHtmlString()).Title("Name").Width(50);
              columns.Bound(c => c.PositionDepartment).Title("Position Department").Width(50);
              columns.Bound(c => c.Gender).Title("Gender").Width(20);
              columns.Bound(c => c.MentorFullName).Title("Mentor").Width(50);
          })
        .HtmlAttributes(new { style = "height: 375px;" })
        .Scrollable(scrollable => scrollable.Height(375))
                .Sortable(sortable => sortable.AllowUnsort(false))
        .Selectable(selectItem => selectItem.Mode(GridSelectionMode.Single))
        .Pageable(pageable => pageable
            .Refresh(true)
            .PageSizes(true)
            // per customer request =>5
            .ButtonCount(5)
        )
        .DataSource(dataSource => dataSource
            .Ajax()
            .Model(model => model.Id(p => p.Id))
                    .Sort(sort =>
                    {
                        sort.Add(Empl => Empl.EmployeeId).Descending(); // <-- intial sort expression
                        sort.Add(fullName => fullName.FullName).Descending();
                        sort.Add(position => position.PositionDepartment).Descending();
                        sort.Add(gender => gender.Gender).Descending();
                        sort.Add(mentor => mentor.MentorFullName).Descending();
                    })
                    .Read(read => read.Action(/* action */"Faculties_Read", /* controller */ "Faculty"))
                    .PageSize(50)
        )
    )
</div>
<script>
    $(function () {
        // Notice that the Name() of the grid is used to get its client-side instance
        var grid = $("#grid").data("kendoGrid");
    });
</script>

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Faculty/_FacultyMenteeMentors.cshtml
@using TraineeTrackingSystem.Web.Common
@model MenteeMentorsViewModel

<div id="mentee-view">
    <input id="reseachId" type="hidden" data-bind="value: selectedId" />

    <script type="text/x-kendo-template" id="mentee-viewLink">
        <div>
            <span>
                <a href='@Url.Action("", "")Mentee/Edit/#= menteeId #'>
                    View Mentee^
                </a>
            </span>
        </div>
    </script>

    <div class="grid-note">
        These are Mentees that are associated with this Faculty Member (Mentor) through the Training Periods on 
        the <a href='@Url.Action("", "")/Mentee/'>Mentee</a> screen.
        <br /><br />
        <b>^</b> = <small>Clicking this link will take you off this page -- you may lose unsaved changes.</small>
    </div>
    
    <div id="menteeGrid" data-role="grid"
         data-editable="false"
         data-selectable="false"
         data-scrollable="true"
         data-sortable="true"
         data-pageable='{ "pageSize": 5 }'
         data-columns="[
                       { 'field': 'ID'},
                       {title:'Name','field': 'menteeFullName'},
                       {title:'Mentee Type','field': 'menteeType'},
                       {title:'Training Period Institution','field': 'institutionName'},
                       {title:'Training Period Start Year','field': 'yearStarted'},
                       {title:'Training Period End Year','field': 'yearEnded'},
                       {title:'Completed Degree','field': 'completedDegree'},
                        {title:'Action', 'width': '130px', template:kendo.template($('#mentee-viewLink').html() ) }
         ]"
         data-bind="source: menteesGridView">
    </div>
</div>
<script>
    $(document).ready(function () {
        var menteeVm = kendo.observable($.extend({
            menteesGridView: new kendo.data.DataSource({
                type: "json",
                serverFiltering: true,
                transport: {
                    read: {
                        url:'@Url.Content("~/CommonData/GetMenteeList")',
                        datatype:"json",
                        data: {
                            name: function(){
                                return $("#menteeGrid").data("grid").value();
                            }
                        }
                    }
                }
            }),
        },@(Html.ToJson(Model))));
        //window.console && console.log(menteeVm);
        kendo.bind($("#mentee-view"), menteeVm);
        $("#menteeGrid").data("kendoGrid").hideColumn(0);
    })
</script>

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Faculty/_FacultyOtherFundingInfo.cshtml
@using TraineeTrackingSystem.Web.Common
@model OtherFundingsInfo

<div id="other-view">
    <input id="reseachId" type="hidden" data-bind="value: selectedId" />
    <h2 class="section-title">Other</h2>
    <script type="text/x-kendo-template" id="otherfund-viewLink">
        <div>
            <span>
                <a href='@Url.Action("", "")/Funding/Edit/#= id #'>
                    View Fund^
                </a>
            </span>
        </div>
    </script>

    @*MVN - keeps these for future ref*@ 
    @*<script id="startDateTemplate" type="text/x-kendo-template">
        #= (dateTimeFundingStarted == null) ? " " : kendo.toString(dateTimeFundingStarted, "dd MMMM yyyy") #
    </script>

    <script id="endDateTemplate" type="text/x-kendo-template">
        #= (dateTimeFundingEnded == null) ? " " : kendo.toString(dateTimeFundingEnded, "dd MMMM yyyy") #
    </script>*@

    <div class="grid-note">
        These are Pending and Active Funds that are associated with this Faculty Member.<br />
        To Add, go to <a href='@Url.Action("", "")/Funding/'>Funding</a>
        <br /><br />
        <b>^</b> = <small>Clicking this link will take you off this page -- you may lose unsaved changes.</small>
    </div>

    <div id="otherGrid" data-role="grid"
         data-editable="false"
         data-selectable="false"
         data-scrollable="true"
         data-sortable="true"
         data-pageable='{ "pageSize": 5 }'
         data-columns="[
                       { 'field': 'facultyPersonId'},
                       { 'field': 'id'},
                       {title:'Role','field':'facultyRole'},
                       {title:'Title','field': 'title'},
                       {title:'Sponsor','field':'sponsorName'},
                       {title:'Sponsor Award #',width:120,'field':'sponsorAwardNumber'},
                       {title:'Start Date','field': 'strDateTimeFundingStarted'},
                       {title:'End Date','field': 'strDateTimeFundingEnded'},
                       {title:'Action', 'width': '130px', template:kendo.template($('#otherfund-viewLink').html() ) }

         ]"
         data-bind="source: otherGridView">
    </div>

</div>

<script>
    $(document).ready(function () {
        var otherFundingVM = kendo.observable($.extend({
            otherGridView: new kendo.data.DataSource({
                type: "json",
                serverFiltering: true,
                transport: {
                    read: {
                        url:'@Url.Content("~/CommonData/GetOtherFundingList")',
                        datatype:"json",
                        data: {
                            name: function(){
                                return $("#otherGrid").data("grid").value();
                            }
                        }
                    }
                }
            }),
        },@(Html.ToJson(Model))));
        kendo.bind($("#other-view"), otherFundingVM);
        $("#otherGrid").data("kendoGrid").hideColumn(0);
        $("#otherGrid").data("kendoGrid").hideColumn(1);
    })
</script>