TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Controllers/UserController.cs
//using Kendo.Mvc.UI;
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Web;
//using System.Web.Mvc;
//using TraineeTrackingSystem.Data;
//using TraineeTrackingSystem.Repository;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using TraineeTrackingSystem.Common;
using TraineeTrackingSystem.Repository;
using TraineeTrackingSystem.Data;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using TraineeTrackingSystem.Web.Common;
using TraineeTrackingSystem.Web.PostModels;
using TraineeTrackingSystem.Web.ViewModels;
// added tracking date and user update
using System.Security.Claims;
using TraineeTrackingSystem.Web.Models;
using System.Net;


namespace TraineeTrackingSystem.Web.Controllers
{
    /// <summary>
    /// MVN - this will be used for User Management
    /// </summary>
    [Authorize]
    [AuthorizeUser(AccessLevel = "Administrator")] 
    public class UserController : Controller
    {
        private readonly CommonDataRepository commonRepository;
        private readonly UserRepository userRepository;
        //private readonly UserRolesRepository usrRoleRepository;
        private TTSEntities db = new TTSEntities();
        private readonly TTSEntities _context;
        string inValidationResult = "ERROR! Not Unique record. Not saved.";
        private readonly string _LastUpdateDATEFORMAT = "{0:M/dd/yyy hh:mm:tt}";
        /// mvn - build User Management constructor
        public UserController()
        {
            _context = new TTSEntities();
            this.userRepository = new UserRepository(_context);
            this.commonRepository = new CommonDataRepository(_context);
        }
        protected override void Dispose(bool disposing)
        {
            userRepository.Dispose();
            base.Dispose(disposing);
        }
        /// <summary>
        /// MVN - this will be used for the User management landing page
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [AcceptVerbs(HttpVerbs.Get)]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult Index()
        {
            //return View();
            var usersIndex = userRepository.GetPersonRoleFromViewTbSearch_VwPersonRoles();
            //var usersIndex = userRepository.GetUserFromViewTbSearch_VwLogins();
            return View(usersIndex);
        }
        public ActionResult Users_Read([DataSourceRequest] DataSourceRequest request)
        {
            //return Json(userRepository.GetPersonRoleFromViewTbSearch_VwPersonRoles().ToDataSourceResult(request));
            //return Json(userRepository.GetUserFromViewTbSearch_VwLogins().ToDataSourceResult(request));
            return Json(userRepository.GetPersonRoleFromViewTbSearch_VwPersonRoles().ToDataSourceResult(request));
        }
        
        // GET: User/Create
        /// <summary>
        /// MVN - Update Intelecent Help info 4/27/2016
        /// This will be called when the UI Create Button is click, essentially load the view 
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }
       /// <summary>
       /// MVN - this handle HTTP request handler 
       /// </summary>
       /// <param name="inValidationRslt"></param>
       /// <returns></returns>
        protected ActionResult HandledBadRequestContentActionResult(string inValidationRslt)
        {
            return Content(inValidationRslt);
        }
        /////////// <summary>
        /////////// MVN - 5/4/2016 
        /////////// I am adding this for future expansion to get user info from AD, passing in user userName, firstName and LastName
        /////////// </summary>
        /////////// <param name="userMedID"></param>
        /////////// <param name="userFName"></param>
        /////////// <param name="userLName"></param>
        /////////// <returns></returns>
        ////////[OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        ////////public JsonResult GetUser(string userMedID, string userFName, string userLName)
        ////////{
        ////////    UserRolesRepository usrRoleRepository = new T32UserRolesRepository();
        ////////    if (userMedID == null || userMedID.ToLower().Equals("undefined") || userMedID.Trim().Length == 0) return Json("", JsonRequestBehavior.AllowGet);
        ////////    var domainUser = usrRoleRepository.GetMedCenterUser(userFName, userLName, userMedID);
        ////////    if (domainUser == null) return Json("", JsonRequestBehavior.AllowGet);

        ////////    //string medCenterId = "isla08";
        ////////    List<Login> w = new List<Login>();
        ////////    if (userMedID == null) return Json(w, JsonRequestBehavior.AllowGet);
        ////////    var result = usrRoleRepository.GetUserByMedCenterId(userMedID);
        ////////    return Json(result.ToString(a => a.DateLastUpdated), JsonRequestBehavior.AllowGet);
        ////////}

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public JsonResult SearchingASOUsers(string partialName)
        {
            List<OSU.Medical.Entity.Employee> users = new List<OSU.Medical.Entity.Employee>();
            //UserRolesRepository usrRoleRepository = new T32UserRolesRepository();
            if (partialName.Trim().Length > 0)
            {
                var _identity = (System.Security.Claims.ClaimsPrincipal)(this.User);
                List<string> auth_roles = _identity.Claims.Where(c => c.Type == System.Security.Claims.ClaimTypes.Role).Select(c => c.Value).ToList();
                #region
                ///TODO HERE
                //users = usrRoleRepository.GetUsersListByPartialNameFromASOUser(partialName, auth_roles);
                #endregion
            }
            return Json(users, JsonRequestBehavior.AllowGet);
        }   

        [HttpGet]
        [AcceptVerbs(HttpVerbs.Get)]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult Edit(int loginId)
        {
            //var loginRecord = userRepository.GetLoginInfoFROMLoginTbl(loginId);
            var loginRecord = userRepository.GetPersonRoleFromViewTbSearch_VwPersonRolesById(loginId);
            var role = userRepository.GetRoleFromRoleTbl().ToList();
            var userVM = new UsersViewModel{
                LoginId = loginRecord.LoginId,
                PersonId = loginRecord.PersonId,
                LastName = loginRecord.LastName,
                MiddleName = loginRecord.MiddleName,
                FirstName = loginRecord.FirstName,
                Username = loginRecord.Username,
                IsActive = loginRecord.IsActive,
                Rolname = loginRecord.RoleName,
                RoleId = loginRecord.RoleId,//.HasValue ? loginRecord.RoleId.Value: null,
                Roles = role.Select(c => new KeyValuePair<int, string>(c.Id, c.RoleName)),

                StrDateLastUpdated = (loginRecord.DateLastUpdated != null) ? String.Format(_LastUpdateDATEFORMAT, loginRecord.DateLastUpdated) : string.Empty,
                StrLastUpdatedBy = commonRepository.GetLoginInfo(loginRecord.LastUpdatedBy),
            };
            return View(new EditUserViewModel{
                UserViewModel = userVM
            });
        }
        /// <summary>
        /// MVN - Created 4/28/2016 
        /// This will be used for adding new user to the T32 login table, 
        /// when the UI AJAX function call by user click the Create button
        /// NOTE:  This feature only look in the T32 table and check username whether in the table or not
        /// assuming the Admin role already know the AD loginId.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult CreateLoginUser(UserPostModel model)
        {
            /// FIRST - SEARCH the login table to make sure
            /// the MedCenterId is not exist, if exist SEND HttpRequest handler
            /// IF NOT Create new login account in the LOGINS talbe      
            Login newLoginAccount = null;
            if (model.UserName != null){
                if (!(_context.Set<Login>().Any(u => u.Username == model.UserName))){
                    Login newLogin = userRepository.AddNewLoginAcct(model.LastName, model.FirstName, model.MiddleName, model.UserName, (ClaimsPrincipal)User);
                    newLoginAccount = newLogin;
                }else{
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return HandledBadRequestContentActionResult(inValidationResult);
                }
            }
            return Json(newLoginAccount.LoginId);
        }
        public ActionResult UpdateUser(UserPostModel model)
        {
            /// Ensure user exsists in the personRole table
            bool isUpdate = model.LoginId.Equals(null) || !_context.Set<Login>()
                .Any(o => o.LoginId == model.LoginId);

            var userLoginRec = isUpdate
                ? new Login()
                : _context.Set<Login>()
                .Single(p => p.LoginId == model.LoginId);


            userLoginRec.Person.LastName = model.LastName;
            userLoginRec.Person.FirstName = model.FirstName;
            userLoginRec.Person.MiddleName = model.MiddleName;
            userLoginRec.Username = model.UserName;
            userLoginRec.IsActive = model.IsActive;

            userLoginRec.DateLastUpdated = DateTime.Now;
            userLoginRec.LastUpdatedBy = (((ClaimsPrincipal)User)
                    .Claims.Where(p => p.Type == ClaimTypes.Name).FirstOrDefault().Value);
            _context.SaveChanges();

            var recordNotFound = model.LoginId.Equals(0) ||
                                !_context.Set<PersonRole>().Any(pR => pR.LoginId == model.LoginId);
            var newPRInfo = recordNotFound

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Shared/_Layout.cshtml
@*@using MVC5Framework.CommonUtility;*@
@using MVC5Framework.CommonUtility;

@using System.Configuration;
@using Microsoft.AspNet.Identity;
@using TraineeTrackingSystem.Common;

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @*<link rel="stylesheet" href="http://www.osu.edu/assets/fonts/webfonts.css">*@
    <link href="~/Content/toastr.css" rel="stylesheet" />
    @Styles.Render("~/Content/css", "~/Content/kendo/styles/css", "~/Content/themes/OSUWMC/css")

    <!--[if lte IE 8]>
    @Scripts.Render("~/bundles/modernizr")
    <![endif]-->    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/kendo", "~/bundles/osuwmc")
    <script src="~/Scripts/toastr.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <!-- jQuery JavaScript -->
    <script src="~/Scripts/Kendo/js/jquery.min.js"></script>

    <!-- Kendo UI combined JavaScript -->
    <script src="~/Scripts/Kendo/js/kendo.all.min.js"></script>

</head>
<body class="application">
    <header class="application">
        <div class="header">

            <div class="wrapper">
                @if (Html.CheckIfPatialViewExists("_TopNavigationBarBrand"))
                {
                    Html.RenderPartial("_TopNavigationBarBrand");
                }
                <a class="logo" href="@Url.Action("Index", "Home", null, "http", ConfigurationManager.AppSettings["TraineeTrackingSystemHostName"])"><img src="~/content/themes/OSUWMC/images/logo.png" alt="logo" /></a>
            </div>
            @if (Html.CheckIfPatialViewExists("_TopNavigationBar"))
            {
                Html.RenderPartial("_TopNavigationBar");
            }
        </div>
    </header>


    <section class="wrapper">
        @if (Html.CheckIfPatialViewExists("_LoginPartial"))
        {
            Html.RenderPartial("_LoginPartial");
        }

        @RenderBody()
    </section>



    <footer class="application">
        <p class="contact">Application specific footer stuff goes here.</p>
        <a class="leaf"><img src="~/Content/themes/OSUWMC/images/buckeye-leaf-red.png" alt="" /><br>Enterprise Custom Applications</a>
    </footer>


    @Scripts.Render("~/bundles/bootstrap")
    <!--[if lte IE 8]>
    @Scripts.Render("~/bundles/respond")
    <![endif]-->
    @RenderSection("scripts", required: false)
</body>
</html>

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Shared/_MenteeGenInfo-OLD.cshtml
@using TraineeTrackingSystem.Web.Common;

@model TraineeTrackingSystem.Data.Mentee

<div id="contractinfo-view">

    <!--MENTEE ID-->
    <label class="control-label" for="StudentId">Mentee ID:</label>
    <input class="k-textbox" id="StudentId" name="StudentId" type="text" placeholder="xxxx00" validationmessage="Mentee ID is required" 
           data-bind="value: studentId, events: { change : setDataChanged }, disabled: isDisabled" required />
    <span class="k-invalid-msg" data-for="StudentId"></span>

</div>

<script>
    var menteeGenInfoViewModel = kendo.observable({
        homeUrl: "",
        menteeMasterId: "",
        studentId: "",
        @*amount: "0",
        expenses: "0",
        revenue: "0",
        startDate: "",
        endDate: "",
        completionDeadline: "",
        comments: "",
        reviewer: "",
        requestType: "",*@

        dataChanged: false,
        isDisabled: false,


        init: function (values) {
            this.set("homeUrl", values.homeUrl);
            this.set("requestMasterId", values.menteeMasterId);
            this.set("isDisabled", values.isDisabled);
            //this.set("requestType", values.requestType);

            this.set("studentId", '@Model.StudentId');
            @*this.set("amount", '@Model.ContractAmount');
            this.set("expenses", '@Model.Expenses');
            this.set("revenue", '@Model.Revenue');
            this.set("startDate", '@Model.StartDate');
            this.set("endDate", '@Model.EndDate');

            this.set("completionDeadline", '@Model.DesiredCompletionDate');
            this.set("comments", '@Model.Comments.JavaEscape()');
            this.set("reviewer", '@Model.Reviewer.JavaEscape()');*@

            this.createMenteeGenInfoAutoComplete();
            //this.applyValidator();

        },

        createMenteeGenInfoAutoComplete: function () {
            var homeUrl = menteeGenInfoViewModel.get("homeUrl");
            // create Curerncy NumericTextBox from input HTML element
            @*@$("#ContractAmount").kendoNumericTextBox({
                format: "c",
                min: 0
            });

            $("#ContractExpenses").kendoNumericTextBox({
                format: "c",
                min: 0
            });

            $("#ContractRevenue").kendoNumericTextBox({
                format: "c",
                min: 0
            });

            $("#TermStartDate").kendoDatePicker({});
            $("#TermEndDate").kendoDatePicker({});
            $("#CompletionDeadline").kendoDatePicker({});

            $("#RequestedReviewer").kendoDropDownList({
                dataTextField: "Name",
                dataValueField: "Name",
                optionLabel: "- Previously worked with -",
                dataSource: {
                    transport: {
                        read: {
                            dataType: "json",
                            url: homeUrl + "/CommonData/GetReviewers",
                        }
                    }
                }
            });*@
        },

        saveChanges: function () {
            if (this.validate() == false) return false;

            if (this.get("dataChanged") == false) {
                return true;
            }

            var menteeMasterId = menteeGenInfoViewModel.get("menteeMasterId");
            var newMenteeGenInfo =
                      {
                          menteeMasterId: menteeGenInfoViewModel.get("menteeMasterId"),
                          StudentId: menteeGenInfoViewModel.get("studentId"),
                          @*ContractAmount: contractInfoViewModel.get("amount"),
                          Expenses: contractInfoViewModel.get("expenses"),
                          Revenue: contractInfoViewModel.get("revenue"),
                          StartDate: contractInfoViewModel.get("startDate"),
                          EndDate: contractInfoViewModel.get("endDate"),
                          DesiredCompletionDate: contractInfoViewModel.get("completionDeadline"),
                          Comments: contractInfoViewModel.get("comments"),
                          Reviewer: contractInfoViewModel.get("reviewer"),
                          requestType: contractInfoViewModel.get("requestType")*@
                      };


            return $.ajax({
                type: "POST",
                url: contractInfoViewModel.get("homeUrl") + "/Mentee/AddUpdateMenteeGenInfo",
                data: JSON.stringify(newMenteeGenInfo),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (result) {
                    if (typeof console !== "undefined" && typeof console.log !== "undefined") {
                        console.log("mentee " + result.ErrorCode);
                    }

                    if (result.ErrorCode === "0") {
                        //Hide save button
                        contractInfoViewModel.set("dataChanged", false);
                        //contractInfoViewModel.set("requestContractInfoID", result.ReturneId);
                        contractInfoViewModel.applyValidator();
                    }
                    else {
                        alert(result.ErrorCode);
                    }
                },
                error: function (request, status, error) {
                    alert(error);
                }
            });
        },

        setDataChanged: function () {
            this.set("dataChanged", true);
        },


    });


</script>

@*}*@

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Shared/_PersonPartial.cshtml
<div id="createRequest-view">


    <label class="control-label" for="firstName">First Name:</label>
    <input id="firstName" class="add listing" type="text" data-bind="value: firstName, disabled: isDisabled" placeholder=" enter first name" />
    <span class="k-invalid-msg" data-for="FirstName"></span>

    <label class="control-label" for="middleName">Middle Name:</label>
    <input id="middleName" class="add listing" type="text" data-bind="value: middleName, disabled:isDisabled" />
    <span class="k-invalid-msg" data-for="MiddleName"></span>

    <label class="control-label" for="lastName">Last Name:</label>
    <input id="lastName" class="add listing" type="text" data-bind="value: lastName, disabled: isDisabled" placeholder=" enter last name" />
    <span class="k-invalid-msg" data-for="LastName"></span>


    <label class="control-label" for="employeeId">EmployeeID:</label>
    <input id="employeeId" class="add listing" type="text" data-bind="value: employeeId, disabled: isDisabled" placeholder=" enter employeeID" />
    <span class="k-invalid-msg" data-for="EmployeeId"></span>

    <div data-bind="invisible: isDisabled">

        <input class="add button" type="button" value="Search Person" data-bind="click: searchPerson" />
    </div>

</div>

<script>

    $(document).ready(function(){
        
        var personViewMode = {};
        kendo.bind($("#createRequest-view"), personViewMode);
       
    });
</script>

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Shared/_ResearchInterest.cshtml
@*@using TraineeTrackingSystem.Common;*@
@*@model IEnumerable<TraineeTrackingSystem.Data.FacultyResearchInterest>*@ 
@*@model TraineeTrackingSystem.Data.Faculty*@
@using TraineeTrackingSystem.Web.Common
@model FacultyGeneralViewMoel


<div id="researchInterest-view">
    <label class="control-label" for="researchInterest">Research Interest: </label>
    <input id="researchInterest" class="add listing" type="text" data-bind="value: researchInterest, disabled: isDisabled" placeholder="- enter research interest - " />
    <span class="k-invalid-msg" data-for="researchInterest"></span>




    <br />
    <br />
    <!-- GET DEPARTMENT-->
    <label class="control-label" for="FacultyResearchInterest_Organization">department: </label>
    <input id="FacultyResearchInterest_Organization" name="FacultyResearchInterest_Organization" placeholder="- select department -" validationmessage="please provide department"
           data-bind="value: department, events: {change: setDataChanged }"/>
    <span class="k-invalid-msg" data-for="FacultyResearchInterest_Organization"></span>

    <div class="k-select">
        <label>Department: </label>
        <input type="text" id="FacultyResearchInterest_Organization" />
    </div>
    <br />
    <br />    
    <span><input class="add-section" type="button" value="Add Research Interest" data-bind="click: addResearchInterest" /></span>

</div>

<script>
    var researchViewModel = kendo.observable({
        facultyUrl: "",
        personId: "",
        researchInterest: "",
        department: "",
        dataChanged: false,
        isDisabled: false,
        init: function (values) {
            this.set("facultyUrl", values.facultyUrl);
            this.set("personId", values.personId);
            this.set("isDisabled", values.isDisabled);
            this.set("researchInterest", values.researchInterest);
            this.set("department", values.department);
            this.get("researchDataSource").transport.options.read.url = values.facultyUrl + "CommonData/GetFCTYResearchInterest";
            this.createDepartmentDropDowns();
            $("#researchInterest-view").getKendoValidator({});

        },
        researchDataSource: new kendo.data.DataSource({
            transport: {
                read: {
                    url: '',
                    dataType: "json",
                    type: "GET"
                }
            },



            error: function (e) {
                if (e.errors) {
                    alert(e.errors);
                }
            }
        }),

        createDepartmentDropDowns: function () {
            $("#FacultyResearchInterest_Organization").kendoDropDownList({
                dataSource: dataSource,
                dataTextField: "DisplayName",
                dataValueField: "FacultyResearchInterest_Organization",
                dataSource: researchViewModel.get("researchDataSource"),
                optionLable: "- select Department -"
            });
        },
        saveChanges: function () {
            if (this.validate() == false) return false;

            if (this.get("dataChanged") == false) {
                return true;
            }

            var newModel = {
                PersonId: this.get("personId"),
                ResearchInterest: this.get("researchInterest"),
                DepartmentId: this.get("department")
            };

            return $.ajax({
                type: "POST",
                url: researchViewModel.get("facultyUrl") + "/Faculty/AddFCTYResearchInterest",
                data: JSON.stringify(newModel),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (result) {
                    if (typeof console !== "undefined" && typeof console.log !== "undefined") {
                        console.log("Title: " + result.ErrorCode);
                    }

                    if (result.ErrorCode === "0") {
                        //Hide save button
                        titleViewModel.set("dataChanged", false);

                    }
                    else {
                        //Show error message
                        alert(result.ErrorCode);
                    }
                },
                error: function (request, status, error) {

                    alert(error);
                }
            });
        },

        setDataChanged: function () {

            this.set("dataChanged", true);
        },

        validate: function () {
            var validator = $("#researchViewModel").kendoValidator({
                maxlength: function (input) {

                    var maxlength = input.data('maxlength');
                    // if the `data-maxlength attribute was found
                    if (maxlength) {

                        if (input.val() != null && (input.val().length) <= maxlength) {

                            // the fields legth OK
                            return true;

                        } else {

                            //validation fails
                            return false;

                        }
                    }

                    // don't perform any validation on the input
                    return true;

                }
            }).data("kendoValidator");
            if (!validator.validate()) {
                return false;
            }
            return true;
        }
    });

    $(document).ready(function () {

        var isDisabled = ('@ViewBag.isDisabled' == "True");



        var values = {
            personId: '@Model.PersonId',
            homeUrl: '@Url.Action("", "Faculty")',
            isDisabled: isDisabled,
            researchInterest:  '@Model.EmployeeId',

            department: "@Model.PrimaryOrganizationId"

        }

        researchViewModel.init(values);

        kendo.bind($("#researchInterest-view"), researchViewModel);

    });

</script>

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Shared/_TopNavigationBar.cshtml
@using System.Configuration;
@using Microsoft.AspNet.Identity;
@using TraineeTrackingSystem.Web.Models;

<nav class="app-nav">
    <div class="mobile-menu">
        <span class="mobile-icon"></span>
        <span class="respondCount" id="respondCount"></span>
    </div>

    <ul id="myTopicsList">          
        @if (SecurityControl.IsAdminUser(this.User)){
            <li> @Html.ActionLink("Training Grants", "Index", "TrainingGrant")</li>
            <li> @Html.ActionLink("Funding", "Index", "Funding")</li>
            <li> @Html.ActionLink("Applicants", "Index", "Applicant") </li>
            <li> @Html.ActionLink("Faculty", "Index", "Faculty") </li>
            <li> @Html.ActionLink("Mentees", "Index", "Mentee")</li>
            <li> @Html.ActionLink("Reports", "Index", "Report")</li>
            <li> @Html.ActionLink("Admin", "Index", "Admin")</li>
            <li> @Html.ActionLink("Users", "Index", "User")</li>
        }
        @if (SecurityControl.IsEditUser(this.User) && 
            !SecurityControl.IsAdminUser(this.User)){
            <li> @Html.ActionLink("Training Grants", "Index", "TrainingGrant")</li>
            <li> @Html.ActionLink("Funding", "Index", "Funding")</li>
            <li> @Html.ActionLink("Applicants", "Index", "Applicant") </li>
            <li> @Html.ActionLink("Faculty", "Index", "Faculty") </li>
            <li> @Html.ActionLink("Mentees", "Index", "Mentee")</li>
            <li> @Html.ActionLink("Reports", "Index", "Report")</li>
        }
        @if (SecurityControl.IsReaderUser(this.User) && !SecurityControl.IsAdminUser(this.User)&&!SecurityControl.IsEditUser(this.User)){
            <li> @Html.ActionLink("Reports", "Index", "Report")</li>
        }
    </ul>
</nav>

    @*<script>


        $(document).ready(function () {

        })
    </script>*@
@*}*@
@*<li> @Html.ActionLink("Training Grants", "Index","TrainingGrant")</li>
    <li> @Html.ActionLink("Funding", "Index", "Funding")</li>
    <li> @Html.ActionLink("Applicants", "Index", "Applicant" ) </li>
    <li> @Html.ActionLink("Faculty", "Index", "Faculty") </li>
    <li> @Html.ActionLink("Mentees", "Index", "Mentee")</li>
    <li> @Html.ActionLink("Reports", "Index", "Report")</li>
    <li> @Html.ActionLink("Admin", "Index", "Admin")</li>*@
@*<li> @Html.ActionLink("Non-NIH Support", "Index", "Support")</li>*@

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Shared/_TopNavigationBarBrand.cshtml
@*@Html.ActionLink("TraineeTrackingSystem.Web", "Index", "Home", null, new { @class = "navbar-brand" })*@
@*@Html.ActionLink("Trainee Tracking System","Index", "Home", null, new { @class = "navbar-brand" })*@
<h1 class="application-title">Honey Badger</h1>