TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/ViewModels/Mentee/MenteeEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TraineeTrackingSystem.Web.ViewModels.Mentee
{
    public class MenteeEditViewModel
    {
        public System.Guid Id { get; set; }
        public string MenteeId { get; set; }
        public string StudentName { get; set; }
        public int InstitutionId { get; set; }
        public int MedicalRankId { get; set; }
        public int DoctoralLevelId { get; set; }
        public bool IsCurrentStudent { get; set; }
        public int DepartmentId { get; set; }
    }
}

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/ViewModels/MenteePublicationViewModel.cs
using System;

namespace TraineeTrackingSystem.Web.ViewModels
{
    public class MenteePublicationViewModel
    {
        
        public Guid Id { get; set; }
        public Guid PersonId { get; set; }  // PersonId of the Mentee

        public Guid AuthorId { get; set; } // AuthorId
        public string DateEntered { get; set; }

        // FROM Publication table - These use in the UI data-bind value
        public string PMCId { get; set; } // PMCID

        public string PMId { get; set; }
        //public bool IsMenteeFirstAuthor { get; set; } // IsMenteeFirstAuthor
        public int IsMenteeFirstAuthor { get; set; } // IsMenteeFirstAuthor
        //public bool IsAdvisorCoAuthor { get; set; } // IsAdvisorCoAuthor
        public int IsAdvisorCoAuthor { get; set; } // IsAdvisorCoAuthor
        public string AuthorList { get; set; } // AuthorList
        public string Title { get; set; } // Title
        public string Journal { get; set; } // Journal
        public DateTime? DateEpub { get; set; } // DateEpub
        public string Doi { get; set; } // DOI
        public DateTime? DatePublicationLastUpdated { get; set; } // DatePublicationLastUpdated
        public int? YearPublished { get; set; } // YearPublished
        public string Volume { get; set; } // Volume
        public string Issue { get; set; } // Issue
        public string Pagination { get; set; } // Pagination
        public string Citation { get; set; }
        //public string Abstract { get; set; } // Abstract

        public string StrDateLastUpdated { get; set; }

        public string StrLastUpdatedBy { get; set; }
    }
}

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/ViewModels/MenteePublicationsViewModel.cs
using System;
using System.Collections.Generic;

namespace TraineeTrackingSystem.Web.ViewModels
{
    public class MenteePublicationsViewModel
    {
        public Guid PersonId { get; set; }
        public Guid SelectedId { get; set; }
        public string SelectedAuthorid { get; set; }
        public DateTime? SelectedDateEntered { get; set; }
        // FROM Publication table - these use in the UI binding to the data-bind value
        public string SelectedPmcid { get; set; } // PMCID
        public string SelectedPMId { get; set; }
        //public bool SelectedIsMenteeFirstAuthor { get; set; } // UI RADIO button IsMenteeFirstAuthor
        //public bool SelectedIsAdvisorCoAuthor { get; set; } // UI RADIO Button IsAdvisorCoAuthor
        //public int IsMenteeFirstAuthor { get; set; } // IsMenteeFirstAuthor
        //public int IsAdvisorCoAuthor { get; set; } // IsAdvisorCoAuthor
        public string SelectedIsMenteeFirstAuthor { get; set; } // UI RADIO button IsMenteeFirstAuthor
        public string SelectedIsAdvisorCoAuthor { get; set; } // UI RADIO Button IsAdvisorCoAuthor
        public string SelectedAuthorList { get; set; } // RTF AuthorList
        public string SelectedTitle { get; set; } // Title
        public string SelectedJournal { get; set; } // Journal
        public DateTime? SelectedDateEpub { get; set; } // DateEpub
        public string SelectedDoi { get; set; } // DOI
        public DateTime? SelectedDatePublicationLastUpdated { get; set; } // DatePublicationLastUpdated TOBEREPLACE by yearPublish
        public int? SelectedYearPublished { get; set; } // YearPublished
        public string SelectedVolume { get; set; } // Volume
        public string SelectedIssue { get; set; } // Issue
        public string SelectedPagination { get; set; } // Pagination
        public string SelectedCitation { get; set; }
        public string SelectedAbstract { get; set; } // Abstract
        public IEnumerable<MenteePublicationViewModel> MenteePublications { get; set; }
    }
}

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Controllers/MenteeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using TraineeTrackingSystem.Common;
using TraineeTrackingSystem.Repository;
using TraineeTrackingSystem.Data;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using TraineeTrackingSystem.Web.Common;
using TraineeTrackingSystem.Web.PostModels;
using TraineeTrackingSystem.Web.ViewModels;
using System.Security.Claims;
using System.Net;
using System.Xml;
using System.Security.Principal;
using TraineeTrackingSystem.Web.Models;

namespace TraineeTrackingSystem.Web.Controllers
{
    [AuthorizeUser(AccessLevel = "Editor")]
    //[AuthorizeUser(MultipleRoles = "Administor, SuperUser,Editor")]
    public class MenteeController : Controller
    {
        private readonly MenteeRepository menteeRepository;
        private readonly CommonDataRepository commonRepository;
        private readonly TTSEntities _context;
        private readonly string _DATEFORMAT = "{0:yyyy-MM-dd}";     //"{0:MM/dd/yyyy}";
        //This globle variable will be used to convert date to specific format 
        private readonly string _LastUpdateDATEFORMAT = "{0:M/dd/yyy hh:mm:tt}";
        public MenteeController()
        {
            _context = new TTSEntities();
            this.menteeRepository = new MenteeRepository(_context);
            this.commonRepository = new CommonDataRepository(_context);
        }

        protected override void Dispose(bool disposing)
        {
            menteeRepository.Dispose();
            base.Dispose(disposing);
        }

        [HttpGet]
        [AcceptVerbs(HttpVerbs.Get)]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        //[AuthorizeUser(AccessLevel = "SuperUser, Administrator, Editor")]
        // GET: Mentee
        public ActionResult Index()
        {

            var menteeData = menteeRepository.GetSearch_VwMenteeDemographics();
            return View(menteeData);
        }

        // DO NOT DELETE - Called by the Mentee Landing page to display/sort relevant Mentee data in the grid
        public virtual JsonResult Mentees_Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(menteeRepository.GetSearch_VwMenteeDemographics().ToDataSourceResult(request));
        }

        // GET: Mentee/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

 
        // GET: Mentee/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult CreateMentee(MenteePostModel newPersonModel)
        {
            //Create Person, get person Id, and then create mentee
            var newPerson = new Person
            {
                PersonId = Guid.NewGuid(),
                FirstName = newPersonModel.FirstName,
                LastName = newPersonModel.LastName,
                MiddleName = newPersonModel.MiddleName,
                DateCreated = DateTime.Now,
                ///// MVN 
                ///// Track last updated date and user
                DateLastUpdated = DateTime.Now,
                LastUpdatedBy = (((ClaimsPrincipal)User).Claims.Where(p => p.Type == ClaimTypes.Name).FirstOrDefault().Value)
            };

            // 10/8/15: MPC: Removed this extra overhead, since it wasn't even being used or saved
            //Mentee newMentee = new Mentee();
            //newMentee.DateLastUpdated = DateTime.Now;
            //newMentee.LastUpdatedBy = (((ClaimsPrincipal)User).Claims.Where(p => p.Type == ClaimTypes.Name).FirstOrDefault().Value);

            Mentee newMentee = menteeRepository.AddMentee(newPerson, newPersonModel.StudentId, newPersonModel.IsTrainingGrantEligible);//, User);
            
            return Json(newMentee.Id);
        }
        /// <summary>
        /// MVN - This private method is to provide the hiding fields for a more elegant way and much more easily to maintaining.  
        /// If there is logic changed, we can just update this method, as appose to multiple places.  
        /// </summary>
        /// <param name="fdStatusId"></param>
        /// <param name="fundingId"></param>
        private void HideFields(Guid? personId, Guid menteeId)
        {
            var currMentee = menteeRepository.GetMenteeById(menteeId);
            // hidding or displaying the lastUpdate Info for General Information
            ViewBag.LastUpdated = (currMentee.DateLastUpdated.HasValue == false) ? true : false;
            
        }


        // POST: Mentee/Edit/5
        public ActionResult Edit(Guid id)
        {
            var currMentee = menteeRepository.GetMenteeById(id);
            var organizationType = commonRepository.GetOrganizationList().ToList();
            var programList = commonRepository.GetProgramList().ToList();
            var mentorList = commonRepository.GetFacultyList().ToList();
            var states = _context.StateProvinces.OrderBy(s => s.FullName).ToList();
            var countries = _context.Countries.ToList();
            //var trackUsrActivity = commonRepository.GetMTLastUpdateInfo(currMentee.PersonId);
           
            if (currMentee == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
            }
            // Use to get DateLastUpdate and lastUpdatedBy only
           // var mentee = commonRepository.GetMTLastUpdateInfo(currMentee.PersonId);
            var menteeGeneralVMInfo = new MenteeGeneralViewModel
            {
                Id = id,
                PersonId = currMentee.PersonId,

                //StrDateLastUpdated = (trackUsrActivity != null) ? String.Format(_LastUpdateDATEFORMAT, trackUsrActivity.DateLastUpdated) : string.Empty,
                //LastUpdatedBy = (mentee != null) ? mentee.LastUpdatedBy : string.Empty,
                //StrLastUpdatedBy = commonRepository.GetLoginInfo(trackUsrActivity.LastUpdatedBy),

                // 10/8/15: MPC -- Removed extra database hit by using the data already returned in original db call
                StrDateLastUpdated = (currMentee.DateLastUpdated != null) ? String.Format(_LastUpdateDATEFORMAT, currMentee.DateLastUpdated) : string.Empty,
                StrLastUpdatedBy = commonRepository.GetLoginInfo(currMentee.LastUpdatedBy),

                AddressStates = states.Select(s => new KeyValuePair<int, string>(s.Id, s.FullName)),
                AddressCountries = countries.Select(c => new KeyValuePair<int, string>(c.Id, c.Name)),

                FirstName = currMentee.Person.FirstName,
                LastName = currMentee.Person.LastName,
                MiddleName = currMentee.Person.MiddleName,
                StudentId = currMentee.StudentId,

                InstitutionAssociationId = currMentee.InstitutionAssociationId,

                DepartmentId = currMentee.DepartmentId.HasValue ? currMentee.DepartmentId.Value : 0,
                Departments = organizationType.Select(o => new KeyValuePair<int, string>(o.Id, o.DisplayName)),

                //EmailAddress1 = currMentee.Person.ContactEmails.Count(e => e.IsPrimary == true) > 0 ?
                //    currMentee.Person.ContactEmails.FirstOrDefault(e => e.IsPrimary == true).EmailAddress : string.Empty,
                //EmailAddress2 = currMentee.Person.ContactEmails.Count(e => e.IsPrimary == false) > 0 ?
                //    currMentee.Person.ContactEmails.FirstOrDefault(e => e.IsPrimary == false).EmailAddress : string.Empty,

                //PhoneNumber = currMentee.Person.ContactPhones.Count(e => e.IsPrimary == true) > 0 ?
                //    currMentee.Person.ContactPhones.FirstOrDefault(e => e.IsPrimary == true).PhoneNumber : string.Empty,

                //MailingAddressLine1 = currMentee.Person.ContactAddresses.Count(e => e.IsPrimary == true) > 0 ?
                //    currMentee.Person.ContactAddresses.FirstOrDefault(e => e.IsPrimary == true).AddressLine1 : string.Empty,

                //MailingAddressLine2 = currMentee.Person.ContactAddresses.Count(e => e.IsPrimary == true) > 0 ?
                //    currMentee.Person.ContactAddresses.FirstOrDefault(e => e.IsPrimary == true).AddressLine2 : string.Empty,

                //MailingAddressLine3 = currMentee.Person.ContactAddresses.Count(e => e.IsPrimary == true) > 0 ?
                //    currMentee.Person.ContactAddresses.FirstOrDefault(e => e.IsPrimary == true).AddressLine3 : string.Empty,

                //MailingAddressCity = currMentee.Person.ContactAddresses.Count(e => e.IsPrimary == true) > 0 ?
                //    currMentee.Person.ContactAddresses.FirstOrDefault(e => e.IsPrimary == true).City : string.Empty,

                //MailingAddressStateId = currMentee.Person.ContactAddresses.Count(e => e.IsPrimary == true) > 0
                //    && currMentee.Person.ContactAddresses.FirstOrDefault(e => e.IsPrimary == true).StateId.HasValue ?
                //    currMentee.Person.ContactAddresses.FirstOrDefault(e => e.IsPrimary == true).StateId.Value : 0,

                //MailingAddressPostalCode = currMentee.Person.ContactAddresses.Count(e => e.IsPrimary == true) > 0 ?
                //    currMentee.Person.ContactAddresses.FirstOrDefault(e => e.IsPrimary == true).PostalCode : string.Empty,

                //MailingAddressCountryId = currMentee.Person.ContactAddresses.Count(e => e.IsPrimary == true) > 0
                //    && currMentee.Person.ContactAddresses.FirstOrDefault(e => e.IsPrimary == true).CountryId.HasValue ?
                //    currMentee.Person.ContactAddresses.FirstOrDefault(e => e.IsPrimary == true).CountryId.Value : 1,

                IsTrainingGrantEligible = currMentee.IsTrainingGrantEligible,
                IsUnderrepresentedMinority = currMentee.Person.IsUnderrepresentedMinority,
                IsIndividualWithDisabilities = currMentee.Person.IsIndividualWithDisabilities,
                IsFromDisadvantagedBkgd = currMentee.Person.IsFromDisadvantagedBkgd
            };

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Controllers/MenteePublicationsController.cs
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Http;
using System.Web.Http.Description;
using TraineeTrackingSystem.Data;

namespace TraineeTrackingSystem.Web.Controllers
{
    public class MenteePublicationsController : ApiController
    {
        private TTSEntities _db = new TTSEntities();

        // GET: api/_Publication
        public IQueryable<Publication> GetPublications()
        {
            return _db.Publications;
        }

        // GET: api/_Publications/5
        [ResponseType(typeof(Publication))]
        public IHttpActionResult GetPublication(int id)
        {
            Publication publication = _db.Publications.Find(id);
            if (publication == null)
            {
                return NotFound();
            }

            return Ok(publication);
        }

        // PUT: api/_Publications/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutPublication(System.Guid id, Publication publication)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != publication.Id)
            {
                return BadRequest();
            }

            _db.Entry(publication).State = EntityState.Modified;

            try
            {
                _db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PublicationExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/_Publications
        [ResponseType(typeof(Publication))]
        public IHttpActionResult PostPublication(Publication publication)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            _db.Publications.Add(publication);
            _db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = publication.Id }, publication);
        }

        // DELETE: api/_Publications/5
        [ResponseType(typeof(Publication))]
        public IHttpActionResult DeletePublication(int id)
        {
            Publication publication = _db.Publications.Find(id);
            if (publication == null)
            {
                return NotFound();
            }

            _db.Publications.Remove(publication);
            _db.SaveChanges();

            return Ok(publication);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool PublicationExists(System.Guid id)
        {
            return _db.Publications.Count(e => e.Id == id) > 0;
        }
    }
}

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Mentee/Edit.cshtml
@using TraineeTrackingSystem.Web.Common;
@model EditMenteeViewModel
@{
    ViewBag.Title = "Edit Mentee";
}

<div class="page-context">
    <div class="context-wrapper">
        <h1 class="page-title">Mentee Form</h1>
    </div>
</div>

<div class="content form">
    <article class="content">
        @*MVN: Trickered edit file to refresh*@
        @*<p class="reminder">Please be sure to save each section as you make edits/updates.</p>*@
        <p class="reminder">Please be sure to save each section as you make edits/updates.</p>
        <!--DONE WITH FORM BUTTON-->
        @*MVN*@
        <!--IN USE ALERT-->
        <!--DISPLAYS CONDITIONALLY-->
        @*<div class="page-alert in-use">This record is currently being edited by [username]</div>*@

        <!-- DISPLAY ID AND LAST EDITED -->
        @*<h1 class="section-title">
            Last updated <label class="control-label" for="DateLastUpdated" data-bind="value: dateLastUpdated" />
            by <label class="control-label" for="LastUpdatedBy" data-bind="value: lastUpdatedBy" />
        </h1>*@

        <!--DONE WITH FORM BUTTON-->
        @*<input class="submit done" type="submit" value="Done" />*@
        <button class="submit done" data-toggle="modal" data-target="#myModal">
            Done
        </button>

        <h1 class="section-title">General Information</h1>
        <div id="hideLastUpdateInfo" hidden="@ViewBag.LastUpdated">
            <p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.MenteeGeneralInfo.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.MenteeGeneralInfo.StrLastUpdatedBy)) </p>
        </div>
            <fieldset name="collectMenteeGenInfo" id="collectMenteeGenInfo" class="two-column-fields">
                @{Html.RenderPartial("_MenteeGeneralInfo", Model.MenteeGeneralInfo);}
            </fieldset>
        
        @*<p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.MenteeGeneralInfo.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.MenteeGeneralInfo.StrLastUpdatedBy)) </p> 
        <fieldset name="collectMenteeGenInfo" id="collectMenteeGenInfo" class="two-column-fields">
            @{Html.RenderPartial("_MenteeGeneralInfo", Model.MenteeGeneralInfo);}
        </fieldset>*@

        @*<h1 class="section-title">Applicant Information</h1>
        <fieldset name="collectMenteeApplicantInfo" id="collectMenteeApplicantInfo" class="two-column-fields">
            @{Html.RenderPartial("_MenteeApplicantInfo", Model.ApplicantInformation);}
        </fieldset>*@

        <h1 class="section-title">Training Period Information</h1>

        @*<div id="hideLastUpdateInfo" hidden="@ViewBag.LastUpdated">
            <p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.MenteeTrainingPeriods.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.MenteeTrainingPeriods.LastUpdatedBy)) </p>
        </div>*@

            @*<p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.MenteeTrainingPeriods.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.MenteeTrainingPeriods.LastUpdatedBy)) </p>*@
            <fieldset name="MenteeTrainingPeriod" id="MenteeTrainingPeriod" class="two-column-fields">
                @{Html.RenderPartial("_MenteeTrainingPeriod", Model.MenteeTrainingPeriods);}
            </fieldset>

            <h1 class="section-title">Academic History</h1>
        @*<div id="hideLastUpdateInfo" hidden="@ViewBag.LastUpdated">
            <p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.MenteeAcademicHistories.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.MenteeAcademicHistories.LastUpdatedBy)) </p>
        </div>*@
            @*<p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.MenteeAcademicHistories.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.MenteeAcademicHistories.LastUpdatedBy)) </p>*@
            <fieldset name="MenteeAcademicHistory" id="MenteeAcademicHistory" class="two-column-fields">
                @{Html.RenderPartial("_MenteeAcademicHistory", Model.MenteeAcademicHistories);}
            </fieldset>

            <h1 class="section-title">Current Mentee Current Support</h1>     
        @*<div id="hideLastUpdateInfo" hidden="@ViewBag.LastUpdated">
            <p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.MenteeSupports.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.MenteeSupports.LastUpdatedBy)) </p>
        </div>*@
            @*<p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.MenteeSupports.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.MenteeSupports.LastUpdatedBy)) </p>*@
            <fieldset name="MenteeCurrentSupport" id="MenteeCurrentSupport" class="two-column-fields">
                @{Html.RenderPartial("_MenteeCurrentSupport", Model.MenteeSupports);}
            </fieldset>

            <h1 class="section-title">Past Trainee Current Position</h1>
        @*<div id="hideLastUpdateInfo" hidden="@ViewBag.LastUpdated">
            <p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.TraineePositions.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.TraineePositions.LastUpdatedBy)) </p>
        </div>*@
            @*<p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.TraineePositions.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.TraineePositions.LastUpdatedBy)) </p>*@
            <fieldset name="PastTraineeCurrentPosition" id="PastTraineeCurrentPosition" class="two-column-fields">
                @{Html.RenderPartial("_TraineeCurrentPosition", Model.TraineePositions);}
            </fieldset>

            <h1 class="section-title">Publications</h1>
            <fieldset name="MenteePublications" id="MenteePublications" class="two-column-fields">
                @{Html.RenderPartial("_MenteePublication", Model.MenteePublications);}
            </fieldset>

            <!--DONE WITH FORM BUTTON-->
            @*<input class="submit done" type="submit" value="Done" />*@
            <button class="submit done" data-toggle="modal" data-target="#myModal">
                Done
            </button>
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Exit Confirmation</h4>
                        </div>
                        <div class="modal-body">
                            This action will take you to the menu, and unsaved changes will be lost.
                        </div>
                        <div class="modal-footer">
                            <button class="add-section" onclick="window.location = '@Url.Content("~/Mentee/Index/")'">OK</button>
                            <button type="button" class="add-section" data-dismiss="modal">Cancel</button>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->

</article>
</div>

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Mentee/Index.cshtml
@model IEnumerable<Search_VwMenteeDemographics>
@using TraineeTrackingSystem.Web.Models;
@{
    ViewBag.Title = "Mentee Index";
}
<div class="page-context">
    <div class="context-wrapper">
        <h1 class="page-title">Mentees</h1>
    </div>
</div>

<div class="content form">
    <article class="content">
       @*@if (SecurityControl.IsAdminUser(this.User) ||
                     SecurityControl.IsEditUser(this.User)){*@
        @if (SecurityControl.IsReaderUser(this.User))
        {
            <div class="section-admin">

                @using (Html.BeginForm("Create", "Mentee"))
                {
                    @*<button id="btnAddMentee" type="submit" class="add-item program" data-bind="visible:addMenteeButtonVisible">+ Add Mentee</button>*@
                    <button type="submit" class="add-item program">+ Add Mentee</button>
                }
            </div>

            <div class="wide-grid">
                <div id="clientsDb">
                    @{Html.RenderPartial("_MenteeLandingPage", Model);}
                </div>
            </div>
       }
    </article>
</div>

@*<script>
    $(document).ready(function () {
        var self = this;
        //self.test = Request.ServerVariables("SERVER_NAME");
        window.console && console.log(HttpContext.Current.Request.ServerVariables("SERVER_NAME"));

        if (HttpContext.Current.Request.ServerVariables("SERVER_NAME") === "http://test.osumc.edu/") {
            //self.set("addMenteeButtonVisible", false); 
            self.btnAddMentee.visible = false;
        } else {
            //self.set("addMenteeButtonVisible", true);
            self.btnAddMentee.visible = true;
        }
    })
</script>*@

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Mentee/_MenteeLandingPage.cshtml
@model IEnumerable<Search_VwMenteeDemographics>

<div id="clientsDb">   
    @(Html.Kendo().Grid(Model)
        .Name("grid")
        .Columns(columns =>
        {
            columns.Bound(c => c.StudentId).Title("Mentee ID").Width(23);
            columns.Bound(c => c.FullName).ClientTemplate(@Html.ActionLink("#=FullName#", "Edit", new { ID = "#=Id#" }).ToHtmlString()).Title("Name").Width(40);  
            columns.Bound(c => c.IsTrainingGrantEligible).Title("TGE").ClientTemplate("#= IsTrainingGrantEligible ? 'Yes' : 'No' #").Width(10);
            //columns.Bound(c => c.IsCurrentStudent).Title("Status").ClientTemplate("#= IsCurrentStudent ? 'Current' : 'Past' #").Width(20);
            columns.Bound(c => c.Department).Title("Department").Width(40);
            //columns.Template(model => null)
            //    .ClientTemplate("<a href='" + Url.RouteUrl("Default", new { controller = "Mentee", action = "Edit" }) + "/#= Id #'>Edit</a>");
        })
        //.ToolBar(toolbar => toolbar.Template("<a id='createOrderButton' class='k-button k-button-icontext k-grid-add' href='#'>Create order</a>"))
        .HtmlAttributes(new { style = "height: 375px;" })
        //.Filterable()
        .Scrollable(scrollable => scrollable.Height(375))
        .Sortable(sortable => sortable.AllowUnsort(false))
        .Selectable(settings => settings.Mode(GridSelectionMode.Single))
        .Pageable(pageable => pageable
            .Refresh(true)
            .PageSizes(true)
            .ButtonCount(5)
        )
        .DataSource(dataSource => dataSource
            .Ajax()
            .Model(model => model.Id(p => p.StudentId))
            .Sort(sort =>
                {
                    sort.Add(sid => sid.StudentId).Descending(); // <-- intial sort expression
                    sort.Add(fullname => fullname.FullName).Descending();
                    sort.Add(isTGE => isTGE.IsTrainingGrantEligible).Descending();
                    sort.Add(dept => dept.Department).Descending();
                })
            .Read(read => read.Action("Mentees_Read", "Mentee"))
            //.ServerOperation(true)
            .PageSize(50)
        )
     )
    
</div>
<script>
    $(function () {
        // Name() of the grid is used to get its client-side instance
        var grid = $("#grid").data("kendoGrid");
    });
</script>