TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/ViewModels/AcademicHistoriesViewModel.cs
namespace TraineeTrackingSystem.Web.ViewModels
{
    public class AcademicHistoriesViewModel
    {
        public int SelectedId { get; set; }
        public int SelectedInstitutionId { get; set; } // InstitutionId
        public int? SelectedYearStarted { get; set; } // YearStarted
        public int? SelectedYearEnded { get; set; } // YearEnded
        public int? SelectedAcademicDegreeId { get; set; } // AcademicDegreeId
        public string SelectedAreaOfStudy { get; set; } // AreaOfStudy
        public int? SelectedYearDegreeCompleted { get; set; } // YearDegreeCompleted
        public bool SelectedIsUndergraduate { get; set; } // IsUndergraduate
        public string SelectedResearchProjectTitle { get; set; } // ResearchProjectTitle
        public string SelectedDoctoralThesis { get; set; } // DoctoralThesis
        public string SelectedResearchAdvisor { get; set; } // ResearchAdvisor
        public bool SelectedIsResidency { get; set; } // IsResidency
        public int? SelectedResidencyInstitutionId { get; set; } // ResidencyInstitutionId
        public string SelectedResidencySpecialization { get; set; } // ResidencySpecialization
        public string SelectedResidencyPgy { get; set; } // ResidencyPGY
        public string SelectedResidencyAdvisor { get; set; } // ResidencyAdvisor
        public int? SelectedResidencyYearStarted { get; set; } // ResidencyYearStarted
        public int? SelectedResidencyYearEnded { get; set; } // ResidencyYearEnded
        public bool SelectedIsNonMedicalTransfer { get; set; } // IsNonMedicalTransfer
        public bool SelectedIsPhDTransfer { get; set; } // IsPhDTransfer
        public string SelectedLabResearch { get; set; } // LabResearch
        public int? SelectedTrainingDoctoralLevelId { get; set; } // TrainingDoctoralLevelId
        public string SelectedComments { get; set; } // Comments
    }
}

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/ViewModels/AcademicHistoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TraineeTrackingSystem.Web.ViewModels
{
    public class AcademicHistoryViewModel
    {
        // FROM AcademicHistory table
        public Guid Id { get; set; } // Id (Primary key) =>AcademicHistory.Id = Institution.Id
        //public Guid PersonId { get; set; } // PersonId =>AcademicHistory.PersonId = Institution.PersonId
        //public int Id { get; set; }
        //public int? DegreeYear { get; set; }
        // FROM AcademicHistory
        public int? YearStarted { get; set; } // YearStarted - Year Entered 
        public int? YearEnded { get; set; } // YearEnded
        public int? YearDegreeCompleted { get; set; } // YearDegreeCompleted
        public int? InstitutionId { get; set; }
        public string InstitutionName { get; set; }
        public bool IsResidency { get; set; } // IsResidency
        public string AreaOfStudy { get; set; } // AreaOfStudy
        public int? CityId { get; set; }
        public string CityName { get; set; }
        public int? StateId { get; set; }
        public string StateName { get; set; }
        public int? CountryId { get; set; }
        public string CountryName { get; set; }
        public string AcademicDegreeName { get; set; }
        public int? AcademicDegreeId { get; set; }
        public string ResearchProjectTitle { get; set; } // ResearchProjectTitle
        public string DoctoralThesis { get; set; } // DoctoralThesis
        public string ResearchAdvisor { get; set; } // ResearchAdvisor
        public string ResidencyTrainingInstName { get; set; }
        public int? ResidencyInstitutionId { get; set; } // ResidencyInstitutionId 
        public string ResidencyAdvisor { get; set; } // ResidencyAdvisor
        public int? ResidencyYearStarted { get; set; } // ResidencyYearStarted
        public int? ResidencyYearEnded { get; set; } // ResidencyYearEnded
        public string Comments { get; set; } // Comments
        public DateTime? DateLastUpdated { get; set; } // DateLastUpdated
        public string LastUpdatedBy { get; set; } // LastUpdatedBy

        public string StrDateLastUpdated { get; set; }

        public string StrLastUpdatedBy { get; set; }
    }
}

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using TraineeTrackingSystem.Common;
using TraineeTrackingSystem.Repository;
using TraineeTrackingSystem.Data;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using TraineeTrackingSystem.Web.PostModels;
using TraineeTrackingSystem.Web.ViewModels;
using TraineeTrackingSystem.Web.Common;
// added tracking date and user update
using System.Security.Claims;
using TraineeTrackingSystem.Web.Models;

namespace TraineeTrackingSystem.Web.Controllers
{
    [AuthorizeUser(AccessLevel = "Editor")]
    //[AuthorizeUser(MultipleRoles = "Administor, SuperUser,Editor")]
    public class ApplicantController : Controller
    {
        private readonly ApplicantRepository applicantRepository;
        private readonly FacultyRepository facultyRepository;
        private readonly CommonDataRepository commonRepository;
        private readonly TTSEntities _context;
        //This globle variable will be used to convert date to specific format 
        private readonly string _LastUpdateDATEFORMAT = "{0:M/dd/yyy hh:mm:tt}";
        public ApplicantController()
        {
            _context = new TTSEntities();
            applicantRepository = new ApplicantRepository(_context);
            facultyRepository = new FacultyRepository(_context);
            this.commonRepository = new CommonDataRepository(_context);
        }
        protected override void Dispose(bool disposing)
        {
            applicantRepository.Dispose();
            facultyRepository.Dispose();
            commonRepository.Dispose();
            base.Dispose(disposing);
        }
        [HttpGet]
        [AcceptVerbs(HttpVerbs.Get)]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        //[AuthorizeUser(AccessLevel = "SuperUser, Administrator, Editor")]
        public ActionResult Index()
        {
            var facultyApplicantDemographics = applicantRepository.Get_Search_VwApplicantDemographics();
            return View(facultyApplicantDemographics);
        }

        //public ActionResult Create(Organization org, GradeRecord grade, OsuTimeline osu, Program prog)
        public ActionResult Create(Organization org, GradeRecord grade, OsuTimeline osu, Program prog, Applicant apl)
        {
            var organizationType = commonRepository.GetOrganizationList().ToList();
            var programType = commonRepository.GetProgramList().ToList();
            var programList = commonRepository.GetProgramList().ToList();
            var applicantsGeneralViewModel = new ApplicantsGeneralViewModel
            {
                DepartmentId = org.Id,
                Departments = organizationType.Select(o => new KeyValuePair<int, string>(o.Id, o.DisplayName)),     
                ProgramId = prog.Id,
                ///////// MVN - replaced this code, instead
                //////Programs = programList.Select(p => new KeyValuePair<Guid, string>(p.Id, p.Title)),
                //////SelectedPrograms = commonRepository.GetProgFromViewTable().Select(p => p.ProgramId),
                Programs = programType.Select(p => new KeyValuePair<Guid, string>(p.Id, p.Title))
            };
            return View(new EditApplicantViewModel
            {
                ApplicantInformations = applicantsGeneralViewModel
            });
        }


        public ActionResult CreateNewApplicant(ApplicantPostModel newApplicantModel)
        {
            var departmentId = (newApplicantModel.DepartmentId == 0) ? null : newApplicantModel.DepartmentId;
            var yearEntered = (newApplicantModel.YearEntered == 0) ? null : newApplicantModel.YearEntered;
            var newPerson = new Person
            {
                PersonId = Guid.NewGuid(),
                FirstName = newApplicantModel.FirstName,
                LastName = newApplicantModel.LastName,
                MiddleName = newApplicantModel.MiddleName,
                DateCreated = DateTime.Now,

                IsUnderrepresentedMinority = newApplicantModel.IsUnderrepresentedMinority,
                IsIndividualWithDisabilities = newApplicantModel.IsIndividualWithDisabilities,
                IsFromDisadvantagedBkgd = newApplicantModel.IsFromDisadvantagedBkgd,
                DateLastUpdated = DateTime.Now,
                LastUpdatedBy = (((ClaimsPrincipal)User).Claims.Where(p => p.Type == ClaimTypes.Name).FirstOrDefault().Value)
            };
            
            var applicant = new Applicant
            {
                PersonId = newPerson.PersonId,
                DoctoralLevelId = newApplicantModel.DoctoralLevelId,
           
                //DepartmentId = newApplicantModel.DepartmentId,
                DepartmentId = departmentId,
                IsTrainingGrantEligible = newApplicantModel.IsTrainingGrantEligible
            };

            var grade = new GradeRecord
            {
                PersonId = newPerson.PersonId,
            };
            var osutimeLine = new OsuTimeline
            {
                PersonId = newPerson.PersonId,
                //YearEntered = newApplicantModel.YearEntered,
                YearEntered = yearEntered
            };
            Applicant newApplicant = applicantRepository.AddNewApplicant(newPerson, applicant, grade, osutimeLine);
            /// MVN - tracking user activity added 10/01/2015
            newApplicant.DateLastUpdated = DateTime.Now;
            newApplicant.LastUpdatedBy = (((ClaimsPrincipal)User).Claims.Where(p => p.Type == ClaimTypes.Name).FirstOrDefault().Value);
            _context.SaveChanges();

            bool isNew = newApplicantModel.PersonId.Equals(null) || !_context.Set<Person>()
                .Any(o => o.PersonId == newApplicantModel.PersonId);

            // PERSON table =>Many to many
            var newApplicantProg = isNew
                ? new Person()
                : _context.Set<Person>()
                .Include(appProg => appProg.Programs)
                .Single(appProg => appProg.PersonId == newApplicantModel.PersonId);
            // Performing the ADD here>>>
            if (newApplicantModel.ProgramsCollection != null)
            {
                foreach (var selectedProgramId in newApplicantModel.ProgramsCollection)
                {
                    if (newPerson.Programs.All(pro => pro.Id != selectedProgramId))
                    {
                        var addProgram = _context.Set<Program>().Find(selectedProgramId);
                        newPerson.Programs.Add(addProgram);
                    }
                }
            }

            newApplicantProg.PersonId = newApplicantModel.PersonId;
            if (isNew)
            {
                _context.Set<Person>().Add(newApplicantProg);
            }          
            _context.SaveChanges();       

            return Json(newApplicant.Id);         
        }

        public ActionResult CreateNewPredoc(ApplicantPostModel newPreDocModel)
        {
            var newPerson = new Person
            {
                PersonId = newPreDocModel.PersonId
            };
            var newApplicant = new Applicant
            {
                ApplicantId = newPreDocModel.ApplicantId
            };
            var newGPA = new GradeRecord
            {
                PersonId = newPerson.PersonId,
                Gpa = newPreDocModel.Gpa,
                GpaScale = newPreDocModel.GpaScale,
                GreScoreVerbal = newPreDocModel.GreScoreVerbal,
                GrePercentileVerbal = newPreDocModel.GrePercentileVerbal,
                GreScoreQuantitative = newPreDocModel.GreScoreQuantitative,
                GrePercentileQuantitative = newPreDocModel.GrePercentileQuantitative,
                GreScoreAnalytical = newPreDocModel.GreScoreAnalytical,
                GrePercentileAnalytical = newPreDocModel.GreScoreAnalytical,
                GreScoreSubject = newPreDocModel.GreScoreSubject,
                GrePercentileSubject = newPreDocModel.GrePercentileSubject,
                McatScoreVerbalReasoning = newPreDocModel.McatScoreVerbalReasoning,
                McatScorePhysicalSciences = newPreDocModel.McatScorePhysicalSciences,
                McatScoreBiologicalSciences = newPreDocModel.McatScoreBiologicalSciences,
                McatScoreWriting = newPreDocModel.McatScoreWriting,
                McatPercentile = newPreDocModel.McatPercentile
            };
            var osutimeLine = new OsuTimeline
            {
                PersonId = newPerson.PersonId,
                WasInterviewed = newPreDocModel.WasInterviewed,
                AcceptedOffer = newPreDocModel.AcceptedOffer,
                WasAccepted = newPreDocModel.WasAccepted, 
                WasEnrolled = newPreDocModel.WasEnrolled
            };
            Applicant addApplicant = applicantRepository.AddNewPredDocApplicant(newPerson, newApplicant, newGPA, osutimeLine);
            _context.SaveChanges();
            return Json(addApplicant.Id);
        }
        /// <summary>
        /// MVN - This private method is to provide the hiding fields for a more elegant way and much more easily to maintaining.  
        /// If there is logic changed, we can just update this method, as appose to multiple places.  
        /// </summary>
        /// <param name="fdStatusId"></param>
        /// <param name="fundingId"></param>
        private void HideFields(Guid applicantId)
        {
            var currApplicant = applicantRepository.GetApplicantByPersonId(applicantId);  
            // hidding or displaying the lastUpdate Info for General Information
            ViewBag.LastUpdated = (currApplicant.DateLastUpdated.HasValue == false) ? true : false;
            
        }

        public ActionResult Edit(Guid id)
        {
            var currApplicant = applicantRepository.GetApplicantByPersonId(id);           
            // MVN - 11-05-2014 to fix the department sorting issue

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Applicant/Create.cshtml
@using TraineeTrackingSystem.Web.Common;
@model EditApplicantViewModel

@{
    ViewBag.Title = "Create Applicant";
}
<div class="page-context">
    <div class="context-wrapper">
        <h1 class="page-title">Applicant Form</h1>
    </div>
</div>
<div class="content form">
    <article class="content">
        <h1 class="section-title">Applicant Information</h1>
        <fieldset name="applicantGeneralInfo" id="applicantGeneralInfo" class="two-column-fields">
            @{Html.RenderPartial("_ApplicantInformation", Model.ApplicantInformations);}
        </fieldset>    
    </article>
</div>

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Applicant/Delete.cshtml
@*@model TraineeTrackingSystem.Web.Models.Applicant

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Applicant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PersonId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateApplied)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateApplied)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>*@

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Applicant/Details.cshtml
@*@model TraineeTrackingSystem.Web.Models.Applicant

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Applicant</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PersonId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateApplied)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateApplied)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Applicant/Edit.cshtml
@model EditApplicantViewModel
@{
    ViewBag.Title = "Edit Applicant";
}
<div class="page-context">
    <div class="context-wrapper">
        <h1 class="page-title">Applicant Form</h1>
    </div>
</div>
<div class="content form">
    <article class="content">
        <p class="reminder">Please be sure to save each section as you make edits/updates.</p>
        <!--DONE WITH FORM BUTTON-->
        <button class="submit done" data-toggle="modal" data-target="#myModal">
            Done
        </button>

        <h1 class="section-title">Applicant Information</h1>
        <div id="hideLastUpdateInfo" hidden="@ViewBag.LastUpdated">
            <p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.ApplicantGeneralViewModel.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.ApplicantGeneralViewModel.StrLastUpdatedBy)) </p>
        </div>
            <fieldset name="applicantInfo" id="applicantInfo" class="two-column-fields">
                @{Html.RenderPartial("_AutoPopulateApplicantInfo", Model.ApplicantGeneralViewModel);}
            </fieldset>
            <h1 class="section-title">Pre-doc Applicant Information</h1>
            <fieldset name="pre-docApplicantInfo" id="docApplicantInfo" class="two-column-fields">
                @{Html.RenderPartial("_AutoPopulateApplicantPreDocInfo", Model.AppPreViewModel);}
            </fieldset>
            <h1 class="section-title">Post-doc/Professional Applicant Information</h1>
            <fieldset name="pre-docApplicantInfo" id="docApplicantInfo" class="two-column-fields">
                @{Html.RenderPartial("_AutoPopulateApplicantPostDocInfo", Model.AppPostDocViewModel);}
            </fieldset>
            <h1 class="section-title">Academic History</h1>
            @*<p class="lastUpdate">Last Updated @Html.DisplayFor(m => m.AcademicHistoryInformations.StrDateLastUpdated)  by @(Html.DisplayFor(m => m.AcademicHistoryInformations.LastUpdatedBy)) </p>*@
            <fieldset name="AcademicHistory" id="AcademicHistory" class="two-column-fields">
                @{Html.RenderPartial("_AcademicHistory", Model.AcademicHistoryInformations);}
            </fieldset>

            <button class="submit done" data-toggle="modal" data-target="#myModal">
                Done
            </button>

            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Exit Confirmation</h4>
                        </div>
                        <div class="modal-body">
                            This action will take you to the menu, and unsaved changes will be lost.
                        </div>
                        <div class="modal-footer">
                            <button class="add-section" onclick="window.location = '@Url.Content("~/Applicant/Index/")'">OK</button>
                            <button type="button" class="add-section" data-dismiss="modal">Cancel</button>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
</article>
</div>

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Applicant/Index.cshtml
@model IEnumerable<Search_VwApplicantDemographics>
@using TraineeTrackingSystem.Web.Models;
@{
    ViewBag.Title = "Applicant Index";
}

<div class="page-context">
    <div class="context-wrapper">
        <h1 class="page-title">Applicant</h1>
    </div>
</div>
<div class="content form">
    <article class="content">
        @if (SecurityControl.IsReaderUser(this.User)){
            <div class="section-admin">
                @using (Html.BeginForm("Create", "Applicant"))
                {
                    <button type="submit" class="add-item program">+ Add Applicant</button>
                }
            </div>
            <div class="wide-grid">
                <div id="clientsDb">
                    @{Html.RenderPartial("_ApplicantLandingPage", Model);}
                </div>
            </div>
        }
    </article>
</div>

TraineeTrackingSystem.Web/TraineeTrackingSystem.WEB/Views/Applicant/_ApplicantInformation.cshtml
@using TraineeTrackingSystem.Web.Common
@model ApplicantsGeneralViewModel
<div id="applicant-view">
    <input id="reseachId" type="hidden" data-bind="value: selectedId" />         
    <label class="control-label">Applicant Type*: </label>
    <div class="radio-group">
        <input type="radio" name="DoctoralLevelId" value=1 data-bind="checked: doctoralLevelId" required validationmessage="This field is required" /><label>Pre-doc</label>
        <input type="radio" name="DoctoralLevelId" value=2 data-bind="checked: doctoralLevelId" required validationmessage="This field is required" /><label>Post-doc</label>
        <span class="help-inline">
            <span class="k-invalid-msg" data-for="DoctoralLevelId" validationmessage="This field is required"></span>
        </span>
    </div>

    <label class="control-label osu-standard" for="programMultiSelect">Program(s):</label>
    <select id="programMultiSelect" name="programMultiSelect"
            data-role="multiselect"
            data-placeholder="select program(s)"
            data-value-primitive="true"
            data-text-field="value"
            data-value-field="key"
            data-bind="value: programId,source: programs"></select>
    @*<select id="programMultiSelect" name="programMultiSelect"
            data-role="multiselect"
            data-placeholder="select program(s)"
            data-value-primitive="true"
            data-text-field="value"
            data-value-field="key"
            data-bind="value: selectedPrograms,source: programs"></select>*@

        <label class="control-label">Department:</label>
        <input id="departmentDropDown" data-role="dropdownlist"
               data-option-label="select department"
               data-auto-bind="true"
               data-text-field="value"
               data-value-field="key"
               data-bind="value: departmentId, source: departments">
        <span class="k-invalid-msg" data-for="departmentId"></span>

        <label for="inputDegreeYear">Entering Year:</label>
        <input data-role="numerictextbox" name="EnteringYear" value="yearEntered" data-format="####" data-spinners="false" data-bind="value:yearEntered" placeholder=" YYYY" size="4" maxlength="4" />

        <label class="control-label">Training Grant Eligible*: </label>
        <div class="radio-group">
            <input type="radio" name="IsTrainingGrantEligible" value="true" data-bind="checked: isTrainingGrantEligible" required validationmessage="This field is required" /><label>Yes</label>
            <input type="radio" name="IsTrainingGrantEligible" value="false" data-bind="checked: isTrainingGrantEligible" required validationmessage="This field is required" /><label>No</label>  
            <span class="help-inline">
                <span class="k-invalid-msg" data-for="IsTrainingGrantEligible" validationmessage="This field is required"></span>
            </span>
        </div>

    
        <label class="control-label">Underrepresented minority: </label>
        <div class="radio-group">
            <input type="radio" name="IsUnderrepresentedMinority" value=1 data-bind="checked: isUnderrepresentedMinority" /><label>Yes</label>
            <input type="radio" name="IsUnderrepresentedMinority" value=2 data-bind="checked: isUnderrepresentedMinority" /><label>No</label>
            <input type="radio" name="IsUnderrepresentedMinority" value=0 data-bind="checked: isUnderrepresentedMinority" /><label>Not Declared</label>
        </div>
        <label class="control-label">Individual with disability: </label>
        <div class="radio-group">
            <input type="radio" name="IsIndividualWithDisabilities" value=1 data-bind="checked: isIndividualWithDisabilities" /><label>Yes</label>
            <input type="radio" name="IsIndividualWithDisabilities" value=2 data-bind="checked: isIndividualWithDisabilities" /><label>No</label>
            <input type="radio" name="IsIndividualWithDisabilities" value=0 data-bind="checked: isIndividualWithDisabilities" /><label>Not Declared</label>
        </div>
        <label class="control-label">Individual from disadvantaged background: </label>
        <div class="radio-group">
            <input type="radio" name="IsFromDisadvantagedBkgd" value=1 data-bind="checked: isFromDisadvantagedBkgd" /><label>Yes</label>
            <input type="radio" name="IsFromDisadvantagedBkgd" value=2 data-bind="checked: isFromDisadvantagedBkgd" /><label>No</label>
            <input type="radio" name="IsFromDisadvantagedBkgd" value=0 data-bind="checked: isFromDisadvantagedBkgd" /><label>Not Declared</label>
        </div>
        <div id="updateDiv">
            <button class="add-section" data-bind="click: createApplicant">Save</button>
            <button class="add-section" data-toggle="modal" data-target="#myModal">
                Cancel
            </button>
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h4 class="modal-title" id="myModalLabel">Cancel Confirmation</h4>
                        </div>
                        <div class="modal-body">
                            Are you sure you would like to cancel this operation?
                        </div>
                        <div class="modal-footer">
                            <button class="add-section" data-bind="click: cancelCreateApplicant">Yes</button>
                            <button type="button" class="add-section" data-dismiss="modal">No</button>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
        </div>
</div>
<script>
    $(document).ready(function () {
        var applicantVm = kendo.observable($.extend({
            updated: false,
            PersonId: self.personId,
            Id: self.selectedId,
            selectedPrograms: null,
            cancelCreateApplicant: function () {
                var self = this;
                window.location = '@Url.Content("~/Applicant/Index/")';
            },
            createApplicant: function () {
                var self = this;
                var validator = $("#applicant-view").kendoValidator().data("kendoValidator");

                if ((self.isTrainingGrantEligible === null)) {
                    validator.validate();
                    //alert("Training Grant Eligible selected is required to create an Applicant!");
                }else{ 
                    var updateData = {                  
                        Id: self.id,
                        PersonId: self.personId,              
                        doctoralLevelId: self.doctoralLevelId,
                        programsCollection: self.programId,
                        //programsCollection: self.selectedPrograms, 
                        /************** these codes fix the foriegn key column, NULL issue ***/                   
                        //departmentId: self.departmentId,
                        departmentId: self.departmentId != null ?
                            self.departmentId : null,

                        yearEntered: self.yearEntered,
                        //yearEntered: self.yearEntered != null?
                        //    self.yearEntered : null,
                        isTrainingGrantEligible: self.isTrainingGrantEligible,
                        isUnderrepresentedMinority: self.isUnderrepresentedMinority,
                        isIndividualWithDisabilities: self.isIndividualWithDisabilities,
                        isFromDisadvantagedBkgd: self.isFromDisadvantagedBkgd
                    };

                    $.ajax({
                        url: '@Url.Content("~/Applicant/CreateNewApplicant")',
                        data: JSON.stringify(updateData),
                        contentType: "application/json, charset=utf-8",
                        type: "POST",
                        datatype: "json",
                        error: function () {
                            toastr.error('Applicant could not be created!');
                        },
                        success: function (value) {
                            @*
                                MVN We decided that we are not going to validate the department and program at point in time
                                window.console && console.log(self);
                            //window.console && console.log(self.selectedPrograms);
                            //var prgrm = $.grep(self.programsCollection, function(e){ return e.id == value.id; });
                            //alert
                            if (self.departmentId === 0){
                                toastr.warning('Either program or department must have a value prior to saving');                               
                            }else{
                                toastr.success('Update successful!');
                                window.location ='@Url.Content("~/Applicant/Edit/")' + value;
                            }*@
                            toastr.success('Applicant created!');
                            window.location ='@Url.Content("~/Applicant/Edit/")' + value;
                        },
                        complete: function () {
                            window.console && console.log("completed");
                        }
                    });
                }
            }
        },@(Html.ToJson(Model))));
        //window.console && console.log(applicantVm);
        kendo.bind($("#applicant-view"), applicantVm);
    })
</script>

   